# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'The X Bar'
tagline:          'A Statistics Blog'
description:      "A place for a normal graduate student to dump his thoughts. I'm unbiased. I swear."
url:              http://jhonaker.github.io
baseurl:          /

author:
  name:           'John Honaker'
  url:            https://jhonaker.github.io

paginate:         5

# Site variables
disqus:           thexbar
google_analytics: UA-56014020-1

# Post default vars
post:
  comments: true

# Custom vars
social:
  github:           https://github.com/JHonaker/
  email:            TheXBarBlog@gmail.com
