# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'The X Bar'
tagline:          'A Statistics Blog'
description:      'A place for a normal graduate student to dump his thoughts. I\'m unbiased. I swear.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'John Honaker'
  url:            https://jhonaker.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JHonaker/JHonaker.github.io
